### ISSUE TITLE
Figure out how manager stores all the link information

### ISSUE THREAD

**Issue by ianaf100** [ndbarteaux/457-P3#9]
The manager needs a way of storing all the links and their costs, and then be able to split it up for each router. Maybe make a small struct representing each link, and a manager class can have methods for sorting through all of it?

**Comment by ndbarteaux** [comment]
if (setsockopt(server_fd, SOL_SOCKET, SO_REUSEADDR, &yes, sizeof(int)) == -1) {
		            perror("setsockopt");
		            exit(1);
		    }
